// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTn62P2JhSemBugu6t-TgHqLJJ3dq4Hts',
    appId: '1:221882321870:web:eafc32f3c7d30595ba799f',
    messagingSenderId: '221882321870',
    projectId: 'zamse-weefo',
    authDomain: 'zamse-weefo.firebaseapp.com',
    storageBucket: 'zamse-weefo.appspot.com',
    measurementId: 'G-XHC5F0T1G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZJ3MbfZHmkBhlEGZRGZvwsq73nu4edA',
    appId: '1:221882321870:android:3260f724df4153acba799f',
    messagingSenderId: '221882321870',
    projectId: 'zamse-weefo',
    storageBucket: 'zamse-weefo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-Ny2pb0FRIVjse8-TIxz0cTN1S_aEGE',
    appId: '1:221882321870:ios:8452c320d5567c9bba799f',
    messagingSenderId: '221882321870',
    projectId: 'zamse-weefo',
    storageBucket: 'zamse-weefo.appspot.com',
    iosBundleId: 'com.example.automobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx-Ny2pb0FRIVjse8-TIxz0cTN1S_aEGE',
    appId: '1:221882321870:ios:5a5a71b1e44ee8e3ba799f',
    messagingSenderId: '221882321870',
    projectId: 'zamse-weefo',
    storageBucket: 'zamse-weefo.appspot.com',
    iosBundleId: 'com.example.automobile.RunnerTests',
  );
}
